# Generated by Django 5.2.1 on 2025-06-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='complaining_user',
            new_name='apartment_complainer',
        ),
    ]
