# Generated by Django 5.2.1 on 2025-06-09 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_rename_complaining_user_report_apartment_complainer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes_by', to=settings.AUTH_USER_MODEL, verbose_name='Понравившиеся квартиры'),
        ),
    ]
