# Generated by Django 5.2.1 on 2025-06-09 11:15

from django.db import migrations
import phonenumbers


def normalize_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        flat.owner_pure_phone = phonenumbers.parse(flat.owner_pure_phone, 'RU')
        if phonenumbers.is_valid_number(flat.owner_pure_phone):
            flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumbers),
    ]
