# Generated by Django 5.2.1 on 2025-06-09 12:10

from django.db import migrations


def transfer_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        if flat.owners_phonenumber:
            Owner.objects.get_or_create(name=flat.owner, pure_phone=flat.owner_pure_phone,
                                        phonenumber=flat.phonenumber)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(transfer_owners),
    ]
