# Generated by Django 5.2.1 on 2025-06-09 12:20

from django.db import migrations


def transfer_flats_info(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        owner.flats.set(Flat.objects.filter(owner=owner.phonenumber))
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20250609_1710'),
    ]

    operations = [
        migrations.RunPython(transfer_flats_info)
    ]
