# Generated by Django 5.2.2 on 2025-06-10 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250609_1720'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes_by', to=settings.AUTH_USER_MODEL, verbose_name='Лайки квартир'),
        ),
    ]
